EnsJobeetBundle_category:
    pattern:  /ens_category/{slug}
    defaults: { _controller: EnsJobeetBundle:Category:show, page: 1}

ens_category:
    resource: "@EnsJobeetBundle/Controller/"
    type:     annotation
    prefix:   /

ens_jobeet:
    resource: "@EnsJobeetBundle/Controller/"
    type:     annotation
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

